"""empty message

Revision ID: 75c6499fc697
Revises: 15791a4b1d49
Create Date: 2022-06-16 00:20:59.855765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c6499fc697'
down_revision = '15791a4b1d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=10), nullable=True),
    sa.Column('modelo', sa.String(length=10), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('autos')
    # ### end Alembic commands ###
